[package]
name = "rust-wasm-hello-world"
version = "1.0.0"
authors = ["juliettepretot <hi@juliette.sh>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
